name: mobile_speech_recognition
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  google_fonts: ^6.2.1
  sqflite: ^2.4.2
  intl: ^0.19.0
  flutter_carousel_widget: ^3.1.0
  
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  device_preview: ^1.2.0
  
  

flutter:
  uses-material-design: true
